"""initial schema (alerts, silences, audit_log)

Revision ID: 26f9bb55689e
Revises: 
Create Date: 2026-05-08 11:23:02.869452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f9bb55689e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    dialect_name = op.get_bind().dialect.name
    max_24h_check = (
        "ends_at - starts_at <= INTERVAL '24 hours'"
        if dialect_name == "postgresql"
        else "(julianday(ends_at) - julianday(starts_at)) * 24.0 <= 24.0"
    )
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('incident_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('lark_message_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('firing', 'silenced', 'resolved', name='alert_state'), nullable=False),
    sa.Column('oncall_target', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_fingerprint')
    )
    op.create_index('ix_alerts_service', 'alerts', ['service'], unique=False)
    op.create_index('ix_alerts_state_updated_at', 'alerts', ['state', 'updated_at'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('event_source', sa.Enum('flashduty', 'lark', 'alertmanager', 'internal', name='event_source'), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('actor_lark_user_id', sa.String(length=64), nullable=True),
    sa.Column('actor_email_redacted', sa.String(length=255), nullable=True),
    sa.Column('payload_redacted', sa.JSON(), nullable=False),
    sa.Column('result', sa.Enum('success', 'failure', name='audit_result'), nullable=False),
    sa.Column('result_summary', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_source', 'dedup_key', name='uq_audit_event_source_dedup_key')
    )
    op.create_index('ix_audit_operation', 'audit_log', ['operation'], unique=False)
    op.create_index('ix_audit_timestamp_utc', 'audit_log', ['timestamp_utc'], unique=False)
    op.create_index('ix_audit_trace_id', 'audit_log', ['trace_id'], unique=False)
    op.create_table('silences',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('alertmanager_silence_id', sa.String(length=64), nullable=False),
    sa.Column('lark_event_id', sa.String(length=128), nullable=False),
    sa.Column('alert_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('matchers', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('actor_lark_user_id', sa.String(length=64), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_choice', sa.String(length=16), nullable=False),
    sa.Column('state', sa.Enum('active', 'expired', 'cancelled', name='silence_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint(max_24h_check, name='ck_silences_max_24h'),
    sa.ForeignKeyConstraint(['alert_fingerprint'], ['alerts.incident_fingerprint'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alertmanager_silence_id'),
    sa.UniqueConstraint('lark_event_id')
    )
    op.create_index('ix_silences_alert_fingerprint', 'silences', ['alert_fingerprint'], unique=False)
    op.create_index('ix_silences_state_ends_at', 'silences', ['state', 'ends_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_silences_state_ends_at', table_name='silences')
    op.drop_index('ix_silences_alert_fingerprint', table_name='silences')
    op.drop_table('silences')
    op.drop_index('ix_audit_trace_id', table_name='audit_log')
    op.drop_index('ix_audit_timestamp_utc', table_name='audit_log')
    op.drop_index('ix_audit_operation', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_alerts_state_updated_at', table_name='alerts')
    op.drop_index('ix_alerts_service', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
